[versions]
agp = "8.5.1"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
firebase = "33.8.0"
googleServices = "4.4.2"
crashlytics = "3.0.2"
onesignalVersion = "[5.1.6, 5.1.99]"
splashScreen = "1.0.1"
navVersion = "2.8.6"
koin = "3.5.6"
multidex = "2.0.1"
parcelize = "2.0.0-RC1"
lottie = "6.5.1"
glide = "4.16.0"
coroutines = "1.9.0"
datastore = "1.1.2"
retrofit = "2.11.0"
playAppUpdate = "2.1.0"
playReview = "2.0.2"
paging = "3.3.5"
sspsdp = "1.1.1"
lifecycle = "2.8.7"
lifecycleExtension = "2.2.0"
okhttp = "5.0.0-alpha.14"
onesignal = "5.1.13"
googleauth = "20.7.0"
flex = "3.0.0"
compose = "2025.02.00"
objectbox = "5.0.1"
mpandroidchart = "3.1.0"
facebookSdk = "18.0.3"
facebookShimmer = "0.5.0"
ktlint = "12.1.0"
biometric = "1.1.0"
circularImageView = "3.1.0"
workmanager = "2.10.0"
billing = "7.1.0"
room = "2.6.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-google-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleauth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
objectbox-browser = { group = "io.objectbox", name = "objectbox-android-objectbrowser", version.ref = "objectbox" }
objectbox-android = { group = "io.objectbox", name = "objectbox-android", version.ref = "objectbox" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navVersion" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navVersion" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-viewmodel = { group = "io.insert-koin", name = "koin-androidx-viewmodel", version.ref = "koin" }
koin-work = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
onesignal = { module = "com.onesignal:OneSignal", version.ref = "onesignalVersion" }
play-app-update = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "playAppUpdate" }
play-app-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
dimension-sdp = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sspsdp" }
dimension-ssp = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "sspsdp" }
okttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-extension = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycleExtension" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flex" }
compose = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-material-ui = { group = "androidx.compose.material3", name = "material3" }
facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "facebookShimmer" }
facebook-android-sdk = { group = "com.facebook.android", name = "facebook-android-sdk", version.ref = "facebookSdk" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric"  }
circular-imageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circularImageView" }
work-manager = {  group = "androidx.work", name = "work-runtime-ktx", version.ref = "workmanager" }
billing = {  group = "com.android.billingclient", name = "billing-ktx", version.ref = "billing" }
room-runtime = {  group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = {  group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = {  group = "androidx.room", name = "room-compiler", version.ref = "room" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
navigationSafeargs = { id = "androidx.navigation.safeargs", version.ref = "navVersion" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "parcelize" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
